FROM node:20-alpine

WORKDIR /app

# Copy package files from ui folder
COPY ui/package*.json ./
RUN npm install

# Copy all Angular source from ui folder
COPY ui/ ./

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]

